import type { Product } from './types';

export const products: Product[] = [
  {
    id: 'cf-001',
    name: 'AeroCool 52" Ceiling Fan',
    category: 'Ceiling Fan',
    price: 4500,
    image: 'https://placehold.co/400x400.png',
    description: 'A stylish and efficient ceiling fan with remote control.',
    brand: 'Brand A',
  },
  {
    id: 'ef-001',
    name: 'BreezeMax Stand Fan',
    category: 'Electric Fan',
    price: 1800,
    image: 'https://placehold.co/400x400.png',
    description: 'Powerful and quiet stand fan for instant cooling.',
    brand: 'Brand B',
  },
  {
    id: 'pc-001',
    name: 'QuickPot 5L Pressure Cooker',
    category: 'Pressure Cooker',
    price: 2500,
    image: 'https://placehold.co/400x400.png',
    description: 'Durable stainless steel pressure cooker for fast cooking.',
    brand: 'Brand C',
  },
  {
    id: 'vs-001',
    name: 'VoltGuard 4KVA Stabilizer',
    category: 'Voltage Stabilizer',
    price: 3200,
    image: 'https://placehold.co/400x400.png',
    description: 'Protects your appliances from voltage fluctuations.',
    brand: 'Brand A',
  },
  {
    id: 'mg-001',
    name: 'PowerBlend 750W Mixer Grinder',
    category: 'Mixer Grinder',
    price: 3800,
    image: 'https://placehold.co/400x400.png',
    description: 'High-performance mixer grinder with 3 jars.',
    brand: 'Brand D',
  },
  {
    id: 'ac-001',
    name: 'ChillWave Desert Air Cooler',
    category: 'Air Cooler',
    price: 8500,
    image: 'https://placehold.co/400x400.png',
    description: 'High-capacity air cooler for large rooms.',
    brand: 'Brand B',
  },
  {
    id: 'ic-001',
    name: 'InstaHeat Induction Cooktop',
    category: 'Induction Cooktop',
    price: 2800,
    image: 'https://placehold.co/400x400.png',
    description: 'Energy-efficient induction cooktop with touch controls.',
    brand: 'Brand C',
  },
  {
    id: 'tw-001',
    name: 'DosaMaster Non-Stick Tawa',
    category: 'Tawa',
    price: 900,
    image: 'https://placehold.co/400x400.png',
    description: 'Perfect for making crispy dosas and chapatis.',
    brand: 'Brand E',
  },
  {
    id: 'gs-001',
    name: 'FlameKing 3-Burner Gas Stove',
    category: 'Gas Stove',
    price: 4200,
    image: 'https://placehold.co/400x400.png',
    description: 'Toughened glass gas stove with efficient burners.',
    brand: 'Brand D',
  },
  {
    id: 'wg-001',
    name: 'GrindWell 2L Wet Grinder',
    category: 'Wet Grinder',
    price: 6500,
    image: 'https://placehold.co/400x400.png',
    description: 'Table top wet grinder for perfect batter.',
    brand: 'Brand A',
  },
  {
    id: 'cf-002',
    name: 'Moderno 48" Ceiling Fan',
    category: 'Ceiling Fan',
    price: 5200,
    image: 'https://placehold.co/400x400.png',
    description: 'Sleek design with powerful air delivery.',
    brand: 'Brand B',
  },
  {
    id: 'mg-002',
    name: 'SuperMix 550W Mixer Grinder',
    category: 'Mixer Grinder',
    price: 3100,
    image: 'https://placehold.co/400x400.png',
    description: 'Compact and efficient for daily kitchen needs.',
    brand: 'Brand E',
  },
];
