import type { Product } from './types';

export const products: Product[] = [
  {
    id: 'cf-001',
    name: 'Bajaj Tiles Tiles DC 2016 Glacier 67 Litres Personal Room Air Cooler',
    category: 'Air Cooler',
    price: 14290,
    image: '/bajaj_dc_2016_glacier.webp',
    description: 'A stylish and efficient ceiling fan with remote control.',
    brand: 'Brand A',
  },
  {
    id: 'ef-001',
    name: 'PHILIPS Daily Collection HL1632/00 500W JUicer Mixer Grinder',
    category: 'Electric Fan',
    price: 4795,
    image: '/philips_juicer_mixer.avif',
    description: 'Powerful and quiet stand fan for instant cooling.',
    brand: 'Brand B',
  },
  {
    id: 'pc-001',
    name: 'Bajaj Tiles Tiles TC 2007 37 Litres Tower Air Cooler',
    category: 'Pressure Cooker',
    price: 8090,
    image: '/tc-2007.avif',
    description: 'Durable stainless steel pressure cooker for fast cooking.',
    brand: 'Brand C',
  },
  {
    id: 'vs-001',
    name: 'Butterfly Smart Glass 2 Burner Gas Stove',
    category: 'Voltage Stabilizer',
    price: 4995,
    image: '/butterfly-smart.avif',
    description: 'Protects your appliances from voltage fluctuations.',
    brand: 'Brand A',
  },
  {
    id: 'mg-001',
    name: 'USHA Misty Air Icy 3 Blade Pedestal Fan',
    category: 'Mixer Grinder',
    price: 3490,
    image: '/usha_misty_air.avif',
    description: 'High-performance mixer grinder with 3 jars.',
    brand: 'Brand D',
  },
  {
    id: 'ac-001',
    name: 'PHILIPS Daily Collection HL7756/00 750W Mixer Grinder',
    category: 'Air Cooler',
    price: 4985,
    image: '/4985.avif',
    description: 'High-capacity air cooler for large rooms.',
    brand: 'Brand B',
  },
  {
    id: 'ic-001',
    name: 'USHA Turbo DBB Sweep 300 mm Exhaust Fan Metallic Grey',
    category: 'Induction Cooktop',
    price: 2250,
    image: '/turbo-dbb.avif',
    description: 'Energy-efficient induction cooktop with touch controls.',
    brand: 'Brand C',
  },
  {
    id: 'tw-001',
    name: 'Crompton Brisk Air 150 mm Exhaust Fan',
    category: 'Tawa',
    price: 1730,
    image: '/brisk-air-150.avif',
    description: 'Perfect for making crispy dosas and chapatis.',
    brand: 'Brand E',
  },
  {
    id: 'gs-001',
    name: 'Prestige Pic 6.0 V2 Induction Cooktop',
    category: 'Gas Stove',
    price: 5290,
    image: '/prestige_pic.avif',
    description: 'Toughened glass gas stove with efficient burners.',
    brand: 'Brand D',
  },
  {
    id: 'wg-001',
    name: 'SINGER FONTA Water Heater 3 Litres Geyser',
    category: 'Wet Grinder',
    price: 3650,
    image: '/singer_fonta.avif',
    description: 'Table top wet grinder for perfect batter.',
    brand: 'Brand A',
  }
];
